URL ?= ghcr.io/USER/REPO
SEMVER ?= 0.0.0
TAG ?= $(URL)$(SUFFIX):$(SEMVER)

# Shell scripts built with environment variable substitution
%.sh: bin/%.sh.envsubst
	cat $< | TAG=$(TAG) DOLLAR=$$ envsubst > $@
	chmod +x $@

# Docker containers
.PHONY: containers container-jetpack5 container-jetpack6 container-cuda
containers: container-jetpack5 container-jetpack6 container-cuda

container-jetpack5: SUFFIX ?= /jetpack5
container-jetpack5:
	docker build . -t $(TAG) -f etc/docker/Dockerfile.triton-jetpack-focal

container-jetpack6: SUFFIX ?= /jetpack6
container-jetpack6:
	docker build . -t $(TAG) -f etc/docker/Dockerfile.nvcr-triton-containers --build-arg JETPACK=1

container-cuda: SUFFIX ?= /cuda
container-cuda:
	docker build . -t $(TAG) -f etc/docker/Dockerfile.nvcr-triton-containers


# The module itself. Make these targets phony so they get rebuilt even if all you change is the
# docker tag.
.PHONY: module-jetpack5.tar.gz module-jetpack6.tar.gz module-cuda.tar.gz

module-jetpack5.tar.gz: SUFFIX ?= /jetpack5
module-jetpack5.tar.gz: viam-mlmodelservice-triton.sh first_run.sh
	tar czf $@ $^

module-jetpack6.tar.gz: SUFFIX ?= /jetpack6
module-jetpack6.tar.gz: viam-mlmodelservice-triton.sh first_run.sh
	tar czf $@ $^

module-cuda.tar.gz: SUFFIX ?= /cuda
module-cuda.tar.gz: viam-mlmodelservice-triton.sh first_run.sh
	tar czf $@ $^

default: container-jetpack6 module-jetpack6.tar.gz
